# -*- mode:org; mode: flyspell; -*-

#+SETUPFILE: p-common.org
#+LATEX_HEADER: \renewcommand{\Re}{\operatorname{Re}}
#+LATEX_HEADER: \renewcommand{\Im}{\operatorname{Im}}

#+TITLE: Discrete mathematics I. practice - Complex numbers
#+SHORT_TITLE: Complex numbers

1. Express the following numbers in Cartesian form:
   #+ATTR_LATEX: :environment inparaenum
   1) $(3+i)(2+3i)$;
   2) $(1-2i)(5+i)$ ;
   3) $(2-5i)^2$ ;
   4) $(1-i)^3$.

2. Simplify the following expressions:
   #+ATTR_LATEX: :environment inparaenum
   1) $i^3$;
   2) $i^5$;
   3) $i^8$;
   4) $\dfrac{1}{i^2}$;
   5) $\dfrac{1}{i}$;
   6) $\dfrac{1}{i^3}$;
   7) $(1+i)^2$;
   8) $(1+i)^{2013}$;
   9) $\dfrac{(1+i)^{2013}}{(1-i)^{2013}}$.

3. Solve the following quadratic functions over the set of complex numbers:
   1) $x^2+x+1=0$;
   2) $x^2+2x+2=0$;
   3) $x^2+2ix-1=0$.

4. Illustrate the following sets on the complex plane: 
   - $\{z: \ \Re(z+2i)\leq 0 \}$; 
   - $\{z: \ \Re(z+1)\geq \Im(z-3i) \}$; 
   - $\{z: \ |z-i-1|\leq 3 \}$; 
   - $\{z: \ |z-3+2i|=|z+4-i| \}$; 
   - $\{z: \ z=1/\overline{z} \}$; 
   - $\{z: \ z+\overline{z}=0 \}$; 
   - $\{z: \ |z|=iz \}$.
  
5. Express the following numbers in Cartesian form:
   1) $\dfrac{3+4i}{1-2i}$;
   2) $\dfrac{\sqrt{3}-i}{\sqrt{3}+i}$;
   3) $\dfrac{1}{(1+i)^2}$;
   4) $\dfrac{1}{(2-i)(1+2i)}$;
   5) $\dfrac{1}{2+3i}+\dfrac{1}{2-3i}$;
   6) $\dfrac{1}{3+i}+\dfrac{1}{1+7i}$.

6. What is the value of the real numbers $a$ and $b$ if:
   1) $(a+bi)(2-i)=a+3i$;
   2) $(a+i)(1+bi)=3b+ai$.

7. Let $\dfrac{5}{x+yi}+\dfrac{2}{1+3i}=1$, where $x$ and $y$ are real
   numbers. What are the values of $x$ and $y$?

8. What is the polar form of the following numbers:
   1) $\sqrt{3}+i$;
   2) $1-i$;
   3) $4i$;
   4) $-3$;
   5) $\dfrac{10}{\sqrt{3}-i}$;
   6) $\dfrac{2+3i}{5+i}$;
   7) $3-4i$;\textbf{h)} $-2+i$.

9. Calculate the values of the following expressions using the polar form: 
   - $\dfrac{(1+i)^9}{(1-i)^7}$;
   - $\left(1-\dfrac{\sqrt{3}-i}{2}\right)^{24}$.
  
10. Solve the following cubic equations:
    - $x^3-7x+6=0$; 
    - $x^3-13x-12=0$; 

11. Write a program to solve cubic equations!
12. To which transformations of the two dimensional plane do the
    following maps correspond to: $z\mapsto 3z+2$; $z\mapsto (1+i)z$;
    $z\mapsto 1/\overline{z}$.

13. Let $z\neq w$ be two complex numbers!  Using $z$ and $w$, express
    the midpoint of the line segment between them, also express the
    third points (angles?) of the two regular triangles defined by $z$
    and $w$ and balance point of these triangles.

14. What is the square root of the following numbers:
    1) $3-4i$;
    2) $2i$;
    3) $-7-24i$;
    4) $8+6i$.

15. Solve the following quadratic equation: $(2+i)x^2-(5-i)x+(2-2i)=0$.

16. Calculate the fifth roots of  $z=-16\cdot \sqrt{3}+16i$!

17. Calculate all the solutions of the following equations:
    1) $x^3=1$;
    2) $x^3=2+2i$;
    3) $x^8=\sqrt{3}-i$;
    4) $x^6=1+i$;

18. What is the fourth root of: $\dfrac{-4}{(2+i)^3}$.

19. Take the following numbers: $1$, $-1$, $i$, $1+i$,
    $(1+i)/\sqrt{2}$, $(1+\sqrt{3}i)/2$, $(-1+\sqrt{3}i)/2$,
    $\cos(\sqrt{2}\pi)+i\sin(\sqrt{2}\pi)$,
    $\cos(\pi/361)+i\sin(\pi/361)$. Which of them are roots of unity,
    what is their order, for which $n$ will they be $n$ -th roots of
    unity, or primitive $n$ -th roots of unity?

20. Show that if  $\varepsilon^4=i$, then $4\mid o(\varepsilon)$.

21. If $o(\varepsilon)=128$, then what is $o(i\cdot \varepsilon)=?$

22. Prove that the set of (integer) exponents of a primitive $n$ -th
    root of unity is the set of $n$ -th roots of unity.

23. Prove that a primitive $n$ -th root of unity is a $k$ -th root of
    unity, if and only if $n\mid k$.

24. Express the value of $\sin(n\alpha)$ and $\cos(n\alpha)$
    using $\sin(\alpha)$, $\cos(\alpha)$!
 
* Solutions
1. HW
2. HW
3. HW
4. HW
5. HW
6. HW
7. Multiply everything with the two denominators:
   \begin{align*}
   5\cdot(1+3i) + 2 \cdot (x+yi) &= (x+yi)\cdot (1+3i) \\
   5 + 15i + 2x + 2yi &= x-3y +i(y + 3x) \\
   \end{align*}
   Then $\Re(lhs) = 5 + 2x = x - 3y = \Re(rhs)$ and $\Im(lhs) = 15 +
   2y = y+3x = \Im(rhs)$. So $x=-5-3y$, and $y=-15+3x$.  Substituting
   the $x$ into the second equation, $y=-15 -15 - 9y$, which gives
   $y=-3$ and $x=4$.
8. HW
9. HW
10. HW
11. HW
12. HW
13. The midpoint halfway between $z$ and $w$ is $m=\frac{z+w}{2}$.

    The other question is a bit more tricky.  The vector from $z$ to
    $w$ is $d=w-z$.  From geometry you should know that the height of
    an equaliteral (regular) triangle is $\sqrt{3}/2$ times the side,
    so $\sqrt{3}/2\cdot d$ has just the right length, but there are
    two things to be fixed: $\sqrt{3}/2 \cdot d$ is not pointing to
    the right direction, the height is perpendicular to the side of a
    triangle, so we need to rotate it 90 degrees left and right, and
    this is $\pm i \cdot \sqrt{3}/2 \cdot d$.  The other trick is,
    that $\pm i \sqrt{3}/2 \cdot d$ starts from the $0$, but we can
    easily fix that, by adding it to the midpoint (where it should
    start) \ie $m\pm i \cdot \sqrt{3}/2 \cdot d = \frac{z+w}{2} \pm i
    \frac{\sqrt{3}}{2} (w-z)$ is the answer.  You should draw the
    steps!
