# -*- mode:org; mode: flyspell; -*-

#+SETUPFILE: p-common.org

#+TITLE: Discrete mathematics I. practice - Relations and functions
#+SHORT_TITLE: Relations and functions

1. Find the $R\cap S$ relation, if $R$ is the $m$ divides $n$ relation
   on $\mathbb{N}$, and $S$ is the $n=m+6$ relation on $\mathbb{Z}$.

2. Let $X=\{a,b,c\}$. Determine the number of all binary relations on
   $X$. Look for examples and counter-examples for properties of
   relations.

3. Let $\textbf{R} \subseteq \mathbb{N} \times \mathbb{N}$ such a
   relation, that $n\textbf{R}m$ $(n,m \in \mathbb{N})$ is true, if
   the number of common divisors of $n$ and $m$ is even. Examine the
   properties of $\textbf{R}$.

4. Look for relations which are
   - reflexive, but not transitive;  
   - anti-symmetric and reflexive;  
   - anti-symmetric and not transitive;  
   - not reflexive, not transitive;  
   - not transitive, but trichotomous;   
   - ``none'' (not reflexive, not transitive, not symmetric, not
     anti-symmetric, not trichotomous).

5. Let us define the following relation on $\mathbb{Z}$ and examine
   its properties:
   - $x\textbf{R}_1y$, if $x^2+y^2$ is divisible by 2; 
   - $x\textbf{R}_2y$, if $x^2-y^2$ is divisible by 2.

6. Given a set $X$ prove that $\sim$ is an equivalence relation! What
   are the classes defined by $\sim$?
   - $X=\C$, $z \sim w$, if $|z|=|w|$;
   - $X=\C$, $z \sim w$, if $z/|z|=w/|w|$;
   - $X=\C$, $z \sim w$, if $z/w=\pm 1$;
   - $X=\C$, $z \sim w$, if $z/w \in \{\pm 1, \pm i\}$;
   - $X=\C$, $z \sim w$, if $(z/w)^n=1$;
   - $X=\Z_{15}$, $x \sim x$, if $5(x-y)\equiv 0 \mod 15$;
   - $X=\N\times \N$, $(p,q) \sim (r,s)$, if $p+s=r+q$;
   - $X=\Z\times \N^+$, $(p,q) \sim (r,s)$, if $pr=sq$.
   #+BEGIN_COMMENT
   %\begin{enumerate}
   % - $X=\C$,  $z \sim w$, if $|z|=|w|$; 
   % - $X=\C$,  $z \sim w$, if $z/|z|=w/|w|$;
   % - $X=\C$,  $z \sim w$, if $z/w=\pm 1$;  
   % - $X=\C$,  $z \sim w$, if $z/w \in \{\pm 1, \pm i\}$;  
   % - $X=\C$,  $z \sim w$, if $(z/w)^n=1$;
   % - $X=\Z_{15}$,  $x \sim x$, if $5(x-y)\equiv 0 \mod 15$;
   % - $X=\N\times \N$,  $(p,q) \sim (r,s)$, if $p+s=r+q$;
   % - $X=\Z\times \N^+$,  $(p,q) \sim (r,s)$, if $pr=sq$. 
   %\end{enumerate}
   #+END_COMMENT

7. Write a program which decides if a relation is reflexive
   (symmetric, anti-symmetric, transitive) or not. Count the number of
   equivalence relations, and the number of partial orderings defined
   on a four element set using the program.

8. Adam and Bob are playing the following game: First Adam selects a
   subset of the $X=\{1, 2, 3\}$ set, then Bob selects a subset of
   $X$, than again Adam and so on.  But they must never select a
   subset which was a subset of a previously selected (sub)set.  The
   loser is the one who makes the last move, which has to be
   selecting the entire $X$ set.  A possible game play: $A: \{1\}$,
   $B: \{2\}$, $A: \{1, 3\}$, $B:\{2,3\}$, $A:\{1,2\}$,
   $B:\{1,2,3\}$, and Adam wins. What is the winning strategy?
9. On the set $\mathbb{N} \times \mathbb{N}$ let us define a relation
   $\mathbf{R}$ the following way: $(m_1,n_1)\mathbf{R}(m_2,n_2)$, if
   $m_1 \le m_2$ and $n_1 \le n_2$. Show that $\mathbf{R}$ is a
   partial ordering.
  
10. Is the following relation a function? $\textbf{R} \subset A \times
    A$, where $A$ is the set of lines in the plane; $a\textbf{R}b$, if
    the lines $a$ and $b$ form an angle of $60^\circ$: Examine the
    properties of this relation (are they: reflexive, transitive,
    symmetric?).

11. Let $A$ be the set of equilateral triangles, which have a
    predefined height $m > 0$ associated with the base of the
    triangle, $B = \{b: b > 0, b\in\mathbb{R}\}$. Let us define the
    relation $\textbf{R} \subseteq A \times B$ as follows:
    $a\textbf{R}b, a \in A, b \in B$, if the area of triangle $a$
    equals $b$. Show that \textbf{R} is a function, and examine its
    properties (is it injective, surjective, bijective).

12. Determine the domain, range of the following relations, decide if
    they and their inverses are functions or not:
    - $\{(x,y)\in \mathbb{R}^2:a<x<b,x<y<2x\}$, where $a,b\in
      \mathbb{R}$ are given numbers;
    - $\{(x,y)\in \mathbb{R}^2:y(1-x^2)=x-1\}$,
    - $\{(x,y)\in \mathbb{R}^2:y=(x-1)/(1-x^2)\}$;
    - $\{(x,y)\in \mathbb{R}^2:|x|+|y|\le 1\}$;
    - $\{(x,y)\in \mathbb{R}^2:x^2=1+y^2,y>0\}$;
    - $\{(x,y)\in \mathbb{R}^2:x^2+y^2-2y<0\}$.

13. Consider the function $f(x) = x/(1-x)$.  It cannot be defined for
    the entire number line.  Which is the widest subset of real
    numbers, for which $f$ can be defined?  Is this function
    injective/surjective/bijective on this subset of real numbers?
    What is the widest subset of $\mathbb{R}$, for which every
    composition $f, f\circ f, f\circ f\circ f, \ldots$ can be defined?
    What can we say about the connection of $f\circ f \circ f$ and
    $f$?

14. For the given relations on $\mathbf{R}$ determine $\dmn
    (\mathbf{R})$, $\rng (\mathbf{R})$. For $A=\{0,1,2\}$ determine the
    image of $A$ i.e. $\mathbf{R}(A)$, preimage $\mathbf{R}^{-1}(A)$,
    restriction $\mathbf{R}\mid_A$:
    1) $\mathbf{R}=\{(x,y)\in\mathbb{Z}_3\times\mathbb{Z}_3: y^2=x\}$, 
    2) $\mathbf{R}=\{(x,y)\in\mathbb{Z}_4\times\mathbb{Z}_4: y^2=x^2\}$, 
    3) $\mathbf{R}=\{(x,y)\in \mathbb{Z}_5\times\mathbb{Z}_5:y^2=x^3+x+1\}$, 
    4) $\mathbf{R}=\{(x,y)\in \mathbb{Z}_7\times\mathbb{Z}_7:y^2=x^3+2\}$.

15. Determine $\mathbf{S}\circ \mathbf{R}$ and $\mathbf{R}\circ
    \mathbf{S}$, if

    - $\mathbf{R}=\{(x,y)\in\mathbb{Z}_3\times\mathbb{Z}_3: y^2=x\}$ and
      $\mathbf{S}=\{(x,y)\in\mathbb{Z}_3\times\mathbb{Z}_3:y=2x\}$;
    - $\mathbf{R}=\{(x,y)\in\mathbb{Z}_4\times\mathbb{Z}_4: y^2=x^2\}$
      and $\mathbf{S}=\{(x,y)\in\mathbb{Z}_4\times\mathbb{Z}_4:y=2x\}$;
    - $\mathbf{R}=\{(x,y)\in\mathbb{Z}_5\times\mathbb{Z}_5:
      y^2=x^3+x+1\}$ and
      $\mathbf{S}=\{(x,y)\in\mathbb{Z}_5\times\mathbb{Z}_5:y^2=x^3+1\}$;
    - $\mathbf{R}=\{(x,y)\in\mathbb{Z}_6\times\mathbb{Z}_6: xy=0\}$ and
      $\mathbf{S}=\{(x,y)\in\mathbb{Z}_6\times\mathbb{Z}_6:x^2+y^2=0\}$;
    - $\mathbf{R}=\{(x,y)\in\mathbb{Z}_7\times\mathbb{Z}_7: xy=1\}$ and
      $\mathbf{S}=\{(x,y)\in\mathbb{Z}_7\times\mathbb{Z}_7:x^2+y^2=1\}$;
    - $\mathbf{R}=\{(x,y)\in\mathbb{Z}_8\times\mathbb{Z}_8: x^2y^2=0\}$
      and $\mathbf{S}=\{(x,y)\in\mathbb{Z}_8\times\mathbb{Z}_8:
      x^2+y^2=0\}$;
 
16. Determine the domain, range, of the following relations, determine
    if they are functions and if their inverses are functions:
    - $\mathbf{R}=\{(x,y)\in\mathbb{Z}_5\times\mathbb{Z}_5: x\cdot y=1\}$;
    - $\mathbf{R}=\{(x,y)\in\mathbb{Z}_6\times\mathbb{Z}_6: x\cdot y=1\}$; 
    - $\mathbf{R}=\{(x,y)\in\mathbb{Z}_5\times\mathbb{Z}_5: x^2+y^2=1\}$; 
    - $\mathbf{R}=\{(x,y)\in\mathbb{Z}_5\times\mathbb{Z}_5: x^4-x=y\}$; 
    - $\mathbf{R}=\{(x,y)\in\mathbb{Z}_7\times\mathbb{Z}_{12}: x^4-x=y\}$; 
    - $\mathbf{R}=\{(x,y)\in\mathbb{Z}_8\times\mathbb{Z}_3: x^4-x=y\}$; 
    - $\mathbf{R}=\{(x,y)\in\mathbb{Z}_8\times\mathbb{Z}_7: x^6=y\}$.

* Solutions
  
