# -*- mode:org; mode: flyspell; -*-

#+SETUPFILE: ../inc/practice.h.org

#+TITLE: Discrete mathematics I. practice - Logic
#+SHORT_TITLE: Logic and sets
* Logic
  1. Considering the set of positive integers, let $P(x)$, $E(x)$,
     $O(x)$, and $D(x, y)$ mean that $x$ is prime, even, odd, and that
     $x$ is divisor of $y$.  Translate the following formulas into
     English.  Determine if they are true.  Negate them formally.
     Negate them in English.  Determine if the negation is true.
     1) $P(7)$; 
     2) $(E(2) \land P(2))$; 
     3) $(\forall x(D(2, x) \Rightarrow E(x)))$; 
     4) $(\exists x(E(x) \land D(x, 6)))$;  
     5) $(\forall x(\neg E(x) \Rightarrow \neg D(2, x)))$; 
     6) $(\forall x(E(x) \Rightarrow (\forall y(D(x, y) \Rightarrow
        E(y)))))$;  
     7) $(\forall x (P(x) \Rightarrow (\exists y (E(y) \land D(x,
        y)))))$; 
     8) $(\forall x(O(x) \Rightarrow (\forall y(P(y) \Rightarrow \neg
        D(x, y)))))$;  
     9) $((\exists x(E(x) \land P(x))) \land (\neg (\exists x(E(x)
        \land P (x) \land (\exists y(\neg x = y \land E(y) \land P
        (y)))))))$. 

  2. Let $S()$, $R()$, $F()$, and $C()$ denote the statements that the
     sun is shining today, it is raining today, it is snowing today, and
     that yesterday it was cloudy. SRFC Translate into English (the
     empty parenthesis are omitted):
     1) $(S \Rightarrow \neg(R \land F))$; 
     2) $(C \Longleftrightarrow S )$; 
     3) $(C \land (S \vee R))$; 
     4) $(S \Longleftrightarrow ((R \land \neg F) \vee C))$;  
     5) $((S \Longleftrightarrow R) \land (\neg F \vee C))$; 

  3. Considering the set of all the people in the world, let $L(x)$,
     $J(x)$, $S(x)$, $O(x)$, $E(x)$, $P(x)$, $R(x)$, $F(x)$, $M(x, y)$,
     and $R(x, y)$ mean that $x$ is a lawyer, judge, smarty pants, old,
     energetic, politician, representative, female, and that $x$ and $y$
     are married, and $x$ respects $y$. Formalise the following
     statements:
     1. every judge is a lawyer;
     2. there are smarty pants lawyers;
     3. there are no smarty pants judges;
     4. some judges are old, but energetic;
     5. judge $d$ is neither old, nor energetic;
     6. except the judges, all lawyers are smarty pants;
     7. some lawyers, who are politicians, are representatives also;
     8. none of the representatives wives are old;
     9. every old representative is a lawyer;
     10. there are women (at least one), who are lawyers and
         representatives;
     11. every woman, who is a lawyer, respects some judges;
     12. some lawyers respect only judges;
     13. there are judges, who respect some women;
     14. some smarty pants don't respect any lawyers;
     15. $d$ doesn't respect any smarty pants;
     16. there are lawyers and smarty pants, who respect judge $d$;
     17. only judges respect judges;
     18. every judge respects only judges;
     19. every married representative is energetic;
     20. the lawyers, with energetic wives are all representatives.

  4. Considering the set of all the people in the world, let $F(x)$ and
     $C(x,y)$ be the predicates for $x$ is female and $x$ is a child of
     $y$. Using these predicated write formulas for $x$ is to $y$ a son,
     daughter, parent, father, mother, grandchild, grandparent,
     grandfather, grandmother, grandfather on the fathers side,
     grandmother on the fathers side, grandfather on the mothers side,
     grandmother on the mothers side, sibling, brother, sister, half
     sibling, cousin, uncle, aunt, nephew and niece.

  5. After introducing the $M(x,y)$ predicate, for $x$, $y$ to be
     married (to the set of predicates from the previous exercise),
     write formulas for the following relations: $x$ is to $y$ a
     husband, wife, brother in law, and sister in law, father in law,
     mother in law, sun in law, daughter in law.

  6. Formalise the following statements:
     1) Marry is not blond;
     2) it is not true, that Mathews is not virtuous enough;
     3) it is raining, but it's warm, although the sun has hidden behind
        the clouds, and it's getting late;
     4) Eve and Peter were there;
     5) if the mountain doesn't go to Mohamed, then Mohamed goes to the
        mountain;
     6) we are going camping, if it's not raining, and neither is the
        wind blowing;
     7) it's impossible, that I wont pass neither math nor physics on
        the first try;
     8) if the witness is reliable, and the fingerprint belongs to the
        perpetrator, then the expert is wrong;
     9) rainbows appear only when it's both raining and the sun is
        shining, but it's not noon;
     10) every door has a knob;
     11) I'm always cold when the wind is blowing.

  7. At a dance girls and boys are dancing. Let us denote that the girl
     $G$ dances with the boy $B$ by writing $D(G,B)$.  Formalise the
     following formulas written in a ``shorthand notation''.  Decide
     which formula is a consequence of another one. (One formula is a
     consequence of another formula, if every time the first one is true
     so is the second one).
     1) $\exists G \forall B \ D(G,B)$,
     2) $\forall B \exists G \ D(G,B)$,
     3) $\exists B \forall G \ D(G,B)$,
     4) $\forall G \exists B \ D(G,B)$, 
     5) $\forall G \forall B \ D(G,B)$, 
     6) $\exists G \exists B \ D(G,B)$; 
     7) $\neg \exists G \exists B \ D(G,B)$,  
     8) $\forall B \exists G \ \neg D(G,B)$, 
     9) $\forall G \exists B \ \neg D(G,B)$,
     10) $\forall G \forall B \ \neg D(G,B)$

  8. There is an island with only knights and thieves. Knights always
     tell the truth, thieves always lie. A visiting tourist meets two
     inhabitants (X and Y). To what group does X and Y belong to if the
     tourists hears the following:
     1) X: Two and two are five. Y: X, you speak nonsense.
     2) X: We're both thieves. Y: Yesterday I went to the cinema.
     3) X: We're both the same. Y: We're different.

  9. A mathematician walks into a bar. He hears that the bartender has 3
     children and ask how old they are. The conversation continues as
     follows:
  
     Bartender: The product of their years is... [we don't hear the
     number just that it's thirty something].\\
     Guest: I can't tell your based only on that information!\\
     Bartender: The sum of their years is the address number of the
     bar.\\
     Guest [goes out side, checks the number]: I still can't figure
     out!\\
     Bartender: The youngest is blond.\\
     Guest: Ahh, now I know the answer!
  
     How old are the kids?
* Logic - solutions
  1. Here are the formalizations a few:
     - $(E(2)\land P(2))$: Two is an even prime.
     - $(\exists x ( E(x) \Rightarrow D(x,6)))$: Six has an even
       divisor.
     - $(\forall x (P(x) \Rightarrow (\exists y (E(y) \land D(x,
       y)))))$: Every prime divides at least one even numbers.  And
       the formal negation: $(\exists x (P(x) \land (\forall y (\lnot
       E(x) \lor \lnot D(x,y)))))$. To get this there you need the
       DeMorgan identities: 
       1) $(\lnot (\forall x P(x))) \iff (\exists x (\lnot P(x)))$,
       2) $(\lnot (\exists x P(x))) \iff (\forall x (\lnot P(x)))$,
       3) $\lnot (\mathcal{A} \land \mathcal{B}) \iff (\lnot \mathcal{A}
          \lor \lnot \mathcal{B})$,
       4) $\lnot (\mathcal{A} \lor \mathcal{B}) \iff (\lnot \mathcal{A}
          \land \lnot \mathcal{B})$,
       and the transformation of implication into a disjunction:
       $(\mathcal{A} \Rightarrow \mathcal{B}) \iff (\lnot \mathcal{A}
       \lor \mathcal{B})$.  - The last one: There is only one even
       prime.
       
     - Here are a few negations.  The rules needed:
       \begin{align*}
       \lnot (\forall x P(x)) &\iff \exists x (\lnot P(x) )\\
       \lnot (\exists x P(x)) &\iff \forall x (\lnot P(x) )\\
       \lnot (A \land B) &\iff (\lnot A) \lor (\lnot B)\\
       \lnot (A \lor B) &\iff (\lnot A) \land (\lnot B)
       \end{align*}
       And the trick with the implication
       \[ A \Rightarrow B \iff \lnot A \lor B \] 
  
       So the answers for (d):
       \begin{align*}
       \lnot (\exists x (E(x) \land D(x,6))) &\iff 
       \forall x \lnot (E(x) \land D(x,6) ) \\ &\iff
       \forall x ( \lnot E(x) \lor \lnot D(x,6) )
       \end{align*}
  
       The answers for (e) (you have to use $\lnot \lnot A \iff
       A$):
       \begin{multline*}
       \lnot (\forall x (\lnot E(x) \Rightarrow \lnot D(2,x))) \iff\\
       \exists x \lnot (\lnot E(x) \Rightarrow \lnot D(2,x)) \iff\\ 
       \exists x \lnot (\lnot \lnot E(x) \lor \lnot D(2,x)) \iff\\
       \exists x \lnot (E(x) \lor \lnot D(2,x)) \iff\\
       \exists x (\lnot E(x) \land D(2,x)) 
       \end{multline*}
       
       The answer for (f):
       \begin{multline*}
       \lnot (\forall x (E(x) \Rightarrow (\forall y (D(x,y)\Rightarrow E(y))))) \iff\\
       \exists x (\lnot(E(x) \Rightarrow (\forall y (D(x,y)\Rightarrow E(y))))) \iff\\
       \exists x (\lnot(\lnot E(x) \lor (\forall y (D(x,y)\Rightarrow E(y))))) \iff\\
       \exists x (E(x) \land \lnot (\forall y (D(x,y)\Rightarrow E(y)))) \iff\\
       \exists x (E(x) \land \exists y (\lnot(D(x,y)\Rightarrow E(y)))) \iff\\
       \exists x (E(x) \land \exists y (\lnot(\lnot D(x,y)\lor E(y)))) \iff\\
       \exists x (E(x) \land \exists y (D(x,y)\land \lnot E(y)))
       \end{multline*}
       

  2. HW.
  3. Some solutions:
     - Every judge is a lawyer. $\forall x (J(x) \Rightarrow L(x))$.
     - Except the judges, all lawyers are smarty pants. $\forall x
       (L(x) \land \lnot J(x)) \Rightarrow S(x)$.
     - Only judges respect judges. $\forall x (\forall y ( (R(x,y)
       \land J(y)) \Rightarrow J(x)))$.
     - Every judge respects only judges. $\forall x (\forall y (
       (R(x,y) \land J(y)) \Rightarrow J(y)))$.
     - The lawyers with energetic wives are all representatives.
       $\forall x ( (L(x)\land ( \exists y (F(y) \land M(x,y) \land
       E(y)) ) \Rightarrow R(x)))$.
  4. Some examples:
     - $Father(x,y) := \lnot F(x) \land C(y,x)$.
     - $Uncle(x,y) := \lnot F(x) \land (\exists g (\exists p ( C(y,p)
       \land C(p,g) \land C(x,g) \land \lnot p = x)))$. Here $x$ is
       the uncle, $y$ is the nephew, $g$ is the uncles parent (nephews
       grandparent), $p$ is the nephews parent.  This definition
       includes ``half uncles''.
  5. HW
  6. HW
  7. HW
  8. Hard! HW
  9. Hard! HW
