# -*- mode:org; mode: flyspell; -*-

#+SETUPFILE: ../include/practice.h.org

#+TITLE: Discrete mathematics I. practice - Basics
#+SHORT_TITLE: Basics
* Basics
** Logic
   1. Considering the set of positive integers, let $P(x)$, $E(x)$,
      $O(x)$, and $D(x, y)$ mean that $x$ is prime, even, odd, and that
      $x$ is divisor of $y$.  Translate the following formulas into
      English.  Determine if they are true.  Negate them formally.
      Negate them in English.  Determine if the negation is true.
      1) $P(7)$; 
      2) $(E(2) \land P(2))$; 
      3) $(\forall x(D(2, x) \Rightarrow E(x)))$; 
      4) $(\exists x(E(x) \land D(x, 6)))$;  
      5) $(\forall x(\neg E(x) \Rightarrow \neg D(2, x)))$; 
      6) $(\forall x(E(x) \Rightarrow (\forall y(D(x, y) \Rightarrow
         E(y)))))$;  
      7) $(\forall x (P(x) \Rightarrow (\exists y (E(y) \land D(x,
         y)))))$; 
      8) $(\forall x(O(x) \Rightarrow (\forall y(P(y) \Rightarrow \neg
         D(x, y)))))$;  
      9) $((\exists x(E(x) \land P(x))) \land (\neg (\exists x(E(x)
         \land P (x) \land (\exists y(\neg x = y \land E(y) \land P
         (y)))))))$. 

   2. Let $S()$, $R()$, $F()$, and $C()$ denote the statements that the
      sun is shining today, it is raining today, it is snowing today, and
      that yesterday it was cloudy. SRFC Translate into English (the
      empty parenthesis are omitted):
      1) $(S \Rightarrow \neg(R \land F))$; 
      2) $(C \Longleftrightarrow S )$; 
      3) $(C \land (S \vee R))$; 
      4) $(S \Longleftrightarrow ((R \land \neg F) \vee C))$;  
      5) $((S \Longleftrightarrow R) \land (\neg F \vee C))$; 

   3. Considering the set of all the people in the world, let $L(x)$,
      $J(x)$, $S(x)$, $O(x)$, $E(x)$, $P(x)$, $R(x)$, $F(x)$, $M(x,
      y)$, and $R(x, y)$ mean that $x$ is a lawyer, a judge, a smarty
      pants, old, energetic, a politician, a representative, female,
      and that $x$ and $y$ are married, and $x$ respects $y$. Formalize
      the following statements:
      1. every judge is a lawyer;
      2. there are smarty pants lawyers;
      3. there are no smarty pants judges;
      4. some judges are old, but energetic;
      5. judge $d$ is neither old, nor energetic;
      6. except the judges, all lawyers are smarty pants;
      7. some lawyers, who are politicians, are representatives also;
      8. none of the representatives wives are old;
      9. every old representative is a lawyer;
      10. there are women (at least one), who are lawyers and
          representatives;
      11. every woman, who is a lawyer, respects some judges;
      12. some lawyers respect only judges;
      13. there are judges, who respect some women;
      14. some smarty pants don't respect any lawyers;
      15. $d$ doesn't respect any smarty pants;
      16. there are lawyers and smarty pants, who respect judge $d$;
      17. only judges respect judges;
      18. every judge respects only judges;
      19. every married representative is energetic;
      20. the lawyers, with energetic wives are all representatives.

   4. Considering the set of all the people in the world, let $F(x)$ and
      $C(x,y)$ be the predicates for $x$ is female and $x$ is a child of
      $y$. Using these predicated write formulas for $x$ is to $y$ a son,
      daughter, parent, father, mother, grandchild, grandparent,
      grandfather, grandmother, grandfather on the fathers side,
      grandmother on the fathers side, grandfather on the mothers side,
      grandmother on the mothers side, sibling, brother, sister, half
      sibling, cousin, uncle, aunt, nephew and niece.

   5. After introducing the $M(x,y)$ predicate, for $x$, $y$ to be
      married (to the set of predicates from the previous exercise),
      write formulas for the following relations: $x$ is to $y$ a
      husband, wife, brother in law, and sister in law, father in law,
      mother in law, sun in law, daughter in law.

   6. Formalise the following statements:
      1) Marry is not blond;
      2) it is not true, that Mathews is not virtuous enough;
      3) it is raining, but it's warm, although the sun has hidden behind
         the clouds, and it's getting late;
      4) Eve and Peter were there;
      5) if the mountain doesn't go to Mohamed, then Mohamed goes to the
         mountain;
      6) we are going camping, if it's not raining, and neither is the
         wind blowing;
      7) it's impossible, that I wont pass neither math nor physics on
         the first try;
      8) if the witness is reliable, and the fingerprint belongs to the
         perpetrator, then the expert is wrong;
      9) rainbows appear only when it's both raining and the sun is
         shining, but it's not noon;
      10) every door has a knob;
      11) I'm always cold when the wind is blowing.

   7. At a dance girls and boys are dancing. Let us denote that the girl
      $G$ dances with the boy $B$ by writing $D(G,B)$.  Formalise the
      following formulas written in a ``shorthand notation''.  Decide
      which formula is a consequence of another one. (One formula is a
      consequence of another formula, if every time the first one is true
      so is the second one).
      1) $\exists G \forall B \ D(G,B)$,
      2) $\forall B \exists G \ D(G,B)$,
      3) $\exists B \forall G \ D(G,B)$,
      4) $\forall G \exists B \ D(G,B)$, 
      5) $\forall G \forall B \ D(G,B)$, 
      6) $\exists G \exists B \ D(G,B)$; 
      7) $\neg \exists G \exists B \ D(G,B)$,  
      8) $\forall B \exists G \ \neg D(G,B)$, 
      9) $\forall G \exists B \ \neg D(G,B)$,
      10) $\forall G \forall B \ \neg D(G,B)$

   8. There is an island with only knights and thieves. Knights always
      tell the truth, thieves always lie. A visiting tourist meets two
      inhabitants (X and Y). To what group does X and Y belong to if the
      tourists hears the following:
      1) X: Two and two are five. Y: X, you speak nonsense.
      2) X: We're both thieves. Y: Yesterday I went to the cinema.
      3) X: We're both the same. Y: We're different.

   9. A mathematician walks into a bar. He hears that the bartender has 3
      children and ask how old they are. The conversation continues as
      follows:
  
      Bartender: The product of their years is... [we don't hear the
      number just that it's thirty something].\\
      Guest: I can't tell your based only on that information!\\
      Bartender: The sum of their years is the address number of the
      bar.\\
      Guest [goes out side, checks the number]: I still can't figure
      out!\\
      Bartender: The youngest is blond.\\
      Guest: Ahh, now I know the answer!
  
      How old are the kids?
** Logic - solutions
   1. Here are the formalizations a few:
      - $(E(2)\land P(2))$: Two is an even prime.
      - $(\exists x ( E(x) \Rightarrow D(x,6)))$: Six has an even
        divisor.
      - $(\forall x (P(x) \Rightarrow (\exists y (E(y) \land D(x,
        y)))))$: Every prime divides at least one even numbers.  And
        the formal negation: $(\exists x (P(x) \land (\forall y (\lnot
        E(x) \lor \lnot D(x,y)))))$. To get this there you need the
        DeMorgan identities: 
        1) $(\lnot (\forall x P(x))) \iff (\exists x (\lnot P(x)))$,
        2) $(\lnot (\exists x P(x))) \iff (\forall x (\lnot P(x)))$,
        3) $\lnot (\mathcal{A} \land \mathcal{B}) \iff (\lnot \mathcal{A}
           \lor \lnot \mathcal{B})$,
        4) $\lnot (\mathcal{A} \lor \mathcal{B}) \iff (\lnot \mathcal{A}
           \land \lnot \mathcal{B})$,
        and the transformation of implication into a disjunction:
        $(\mathcal{A} \Rightarrow \mathcal{B}) \iff (\lnot \mathcal{A}
        \lor \mathcal{B})$.  - The last one: There is only one even
        prime.
       
      - Here are a few negations.  The rules needed:
        \begin{align*}
        \lnot (\forall x P(x)) &\iff \exists x (\lnot P(x) )\\
        \lnot (\exists x P(x)) &\iff \forall x (\lnot P(x) )\\
        \lnot (A \land B) &\iff (\lnot A) \lor (\lnot B)\\
        \lnot (A \lor B) &\iff (\lnot A) \land (\lnot B)
        \end{align*}
        And the trick with the implication
        \[ A \Rightarrow B \iff \lnot A \lor B \] 
  
        So the answers for (d):
        \begin{align*}
        \lnot (\exists x (E(x) \land D(x,6))) &\iff 
        \forall x \lnot (E(x) \land D(x,6) ) \\ &\iff
        \forall x ( \lnot E(x) \lor \lnot D(x,6) )
        \end{align*}
  
        The answers for (e) (you have to use $\lnot \lnot A \iff
        A$):
        \begin{multline*}
        \lnot (\forall x (\lnot E(x) \Rightarrow \lnot D(2,x))) \iff\\
        \exists x \lnot (\lnot E(x) \Rightarrow \lnot D(2,x)) \iff\\ 
        \exists x \lnot (\lnot \lnot E(x) \lor \lnot D(2,x)) \iff\\
        \exists x \lnot (E(x) \lor \lnot D(2,x)) \iff\\
        \exists x (\lnot E(x) \land D(2,x)) 
        \end{multline*}
       
        The answer for (f):
        \begin{multline*}
        \lnot (\forall x (E(x) \Rightarrow (\forall y (D(x,y)\Rightarrow E(y))))) \iff\\
        \exists x (\lnot(E(x) \Rightarrow (\forall y (D(x,y)\Rightarrow E(y))))) \iff\\
        \exists x (\lnot(\lnot E(x) \lor (\forall y (D(x,y)\Rightarrow E(y))))) \iff\\
        \exists x (E(x) \land \lnot (\forall y (D(x,y)\Rightarrow E(y)))) \iff\\
        \exists x (E(x) \land \exists y (\lnot(D(x,y)\Rightarrow E(y)))) \iff\\
        \exists x (E(x) \land \exists y (\lnot(\lnot D(x,y)\lor E(y)))) \iff\\
        \exists x (E(x) \land \exists y (D(x,y)\land \lnot E(y)))
        \end{multline*}
       

   2. HW.
   3. Some solutions:
      - Every judge is a lawyer. $\forall x (J(x) \Rightarrow L(x))$.
      - Except the judges, all lawyers are smarty pants. $\forall x
        (L(x) \land \lnot J(x)) \Rightarrow S(x)$.
      - Only judges respect judges. $\forall x (\forall y ( (R(x,y)
        \land J(y)) \Rightarrow J(x)))$.
      - Every judge respects only judges. $\forall x (\forall y (
        (R(x,y) \land J(y)) \Rightarrow J(y)))$.
      - The lawyers with energetic wives are all representatives.
        $\forall x ( (L(x)\land ( \exists y (F(y) \land M(x,y) \land
        E(y)) ) \Rightarrow R(x)))$.
   4. Some examples:
      - $Father(x,y) := \lnot F(x) \land C(y,x)$.
      - $Uncle(x,y) := \lnot F(x) \land (\exists g (\exists p ( C(y,p)
        \land C(p,g) \land C(x,g) \land \lnot p = x)))$. Here $x$ is
        the uncle, $y$ is the nephew, $g$ is the uncles parent (nephews
        grandparent), $p$ is the nephews parent.  This definition
        includes ``half uncles''.
   5. HW
   6. HW
   7. HW
   8. Hard! HW
   9. Hard! HW
** Sets
   1. Find the sets $A,B,C$ which satisfy the following conditions: \[
      A\cap B \ne \emptyset, \quad A\cap C = \emptyset, \quad (A\cap B)
      \setminus C = \emptyset. \]

   2. Prove that $A \cap B \subseteq C \Leftrightarrow A \subseteq
      \overline{B} \cup C$.

   3. Give a system of sets, which is disjoint but not mutually
      (pairwise) disjoint! Is there a system of sets which is mutually
      disjoint but not disjoint?

   4. Let $\mathcal{A}=\{\{a,b,c\},\{a,d,e\},\{a,f\}\}$. What is $\cup
      \cal A$ and $\cap \cal A$?

   5. Let $x=\{\text{apple, plum}\}$ and $y=\{\text{dog, cat}\}$ be
      sets. For which of these sets is it true that: $x$ in an element,
      a subset of, $x$ is not an element, not subset of: $\{\{x\},y\}$,
      $x$, $\{ \emptyset \} \cap x$, $\{x\} \setminus \{\{x\}\},
      \{x\}\cup x, \{x\} \cup \{\emptyset\}$.

   6. Prove the following:
      1) $A \bigtriangleup \emptyset = A$; \hspace{5mm} 
      2) $A \bigtriangleup A = \emptyset$; \hspace{5mm} 
      3) $A \bigtriangleup (B \bigtriangleup C) = (A \bigtriangleup B)
         \bigtriangleup C$; \hspace{5mm}
      4) $A \bigtriangleup (A \bigtriangleup B)=B$.
  
   7. Using $\bigtriangleup$ and $\cap$ , express the following sets: $A
      \setminus B$ and $A \cup B$.

   8. Simplify the following $(A \cup (A\cap B)\cup (A \cap B \cap
      C))\cap(A\cup B \cup C)$.

   9. Prove that:
      1) $\overline{A \cap B} = \overline{A} \cup \overline{B};$
         \hspace{5mm}
      2) $A \setminus B = A \cap \overline{B};$ \hspace{5mm}
      3) $A \setminus (B \cap C)=(A\setminus B)\cup (A\setminus C);$
         \hspace{5mm}
      4) $A \setminus (B \cup C)= (A \setminus B) \setminus C$.
   10. Identify which statements are true for arbitrary sets $A,B,C$:
       1) $(A\cup B) \setminus A = B$;
       2) $(A\cup B) \setminus C = A\cup (B \setminus C)$;
       3) $(A \setminus B)\cap C = (A \cap C)\setminus B = (A\cap
          C)\setminus (B\cap C)$.

   11. Prove the following relation: $\overline{(\overline{A\cap B}\cup
       C)\cap \overline{A}}\cup \overline{B}\cup \overline{C} = A \cup
       \overline{B} \cup\overline{C}$.

   12. Simplify the following: 
       1) $\overline{A \cup(B\cap(C\cup \overline{D}))}$,
       2) $\overline{(\overline{A}\cup B)\cap(A
          \cup\overline{B})}$.

   13. Write the power set of a 0, 1, 2 and 3 element set.

   14. A group of software engineer lions (who think absolutely
       perfectly) are standing in a circle around a slab of meat. All of
       them would gladly eat, but none of them want to risk their lives
       for it. If one of them eats the meat, he will fall asleep right
       then and from then on, he is a potential lunch for the other
       lions. How will the ultra-smart lions act if
       1) there are 2 of them;
       2) there are 3 of them;
       3) if there are 99 of them;
       4) if there are 100 of them?

   15. There are 50 coins on the table, 25 heads, 25 tails. With our eyes
       covered, how can we make two piles so that both piles have ther
       same amount of coins facing heads.

** Sets - Solutions
   1. $A \cap B \neq \emptyset$, so $\exists x \in A \cap B$, so $A
      \cap C = \emptyset$ implies that $x\not\in A \cap C$, so
      $x\not\in C$, but then $x \in (A\cap B)\setminus C$ \ie $(A \cap
      B) \setminus C = \emptyset$ can not be true.  We have proven
      that there is no solution, \ie there are no such sets which
      satisfy these properties.
   2. HW***
   3. $\mathcal{A}=\{ \{a,b\}, \{b,c\}, \{c,a\}\}$ is disjoint but not
      pairwise disjoint.  Generally, pairwise disjoint sets are
      disjoint, (with the exception of the special case of a single
      non-empty set: \ie $\mathcal{B}=\{\{x\}\}$ is pairwise disjoint,
      but not disjoint).
   4. $\cup\mathcal{A}=\{a,b,c,d,e,f\}$, $\cap\mathcal{A} = \{a\}$.
   5. Let's solve this with a small python program.
      #+BEGIN_SRC python :results output :exports both
        x = ["apple", "plumb"]
        y = ["cat", "dog" ]
        empty = []

        def subset(A,B):
            for a in A:
                if not a in B: return False
            return True

        def intersect(A,B):
            r = []
            for a in A:
                if a in B: r.append(a)
            return r

        def setminus(A,B):
            r = []
            for a in A:
                if not a in B: r.append(a)
            return r

        def union(A,B):
            r = []
            for x in A:
                if not x in r: r.append(x)
            for x in B:
                if not x in r: r.append(x)
            return r
            
        testcases = [
            [[x],y],
            x,
            intersect([empty],x),
            setminus([x],[[x]]),
            union([x],x),
            union([x],[empty])
        ]
        print("The set                                 x in, x subset")
        for t in testcases:
            print( "{:<38}, {:<5}, {:<5}"
                .format(str(t), str(x in t), str(subset(x,t))))
        
      #+END_SRC

      #+RESULTS:
      : [[['apple', 'plumb']], ['cat', 'dog']], False, False
      : ['apple', 'plumb']                    , False, True 
      : []                                    , False, False
      : [['apple', 'plumb']]                  , True , False
      : [['apple', 'plumb'], 'apple', 'plumb'], True , True 
      : [['apple', 'plumb'], []]              , True , False
   6. 
   7. 
   8. 
   9. 
   10. 
   11. 
   12. 
   13. 
   14. 
** Relations
   1. Find the $R\cap S$ relation, if $R$ is the $m$ divides $n$ relation
      on $\mathbb{N}$, and $S$ is the $n=m+6$ relation on $\mathbb{Z}$.

   2. Let $X=\{a,b,c\}$. Determine the number of all binary relations on
      $X$. Look for examples and counter-examples for properties of
      relations.

   3. Let $\textbf{R} \subseteq \mathbb{N} \times \mathbb{N}$ such a
      relation, that $n\textbf{R}m$ $(n,m \in \mathbb{N})$ is true, if
      the number of common divisors of $n$ and $m$ is even. Examine the
      properties of $\textbf{R}$.

   4. Look for relations which are
      - reflexive, but not transitive;  
      - anti-symmetric and reflexive;  
      - anti-symmetric and not transitive;  
      - not reflexive, not transitive;  
      - not transitive, but trichotomous;   
      - ``none'' (not reflexive, not transitive, not symmetric, not
        anti-symmetric, not trichotomous).

   5. Let us define the following relation on $\mathbb{Z}$ and examine
      its properties:
      - $x\textbf{R}_1y$, if $x^2+y^2$ is divisible by 2; 
      - $x\textbf{R}_2y$, if $x^2-y^2$ is divisible by 2.

   6. Given a set $X$ prove that $\sim$ is an equivalence relation! What
      are the classes defined by $\sim$?
      - $X=\C$, $z \sim w$, if $|z|=|w|$;
      - $X=\C$, $z \sim w$, if $z/|z|=w/|w|$;
      - $X=\C$, $z \sim w$, if $z/w=\pm 1$;
      - $X=\C$, $z \sim w$, if $z/w \in \{\pm 1, \pm i\}$;
      - $X=\C$, $z \sim w$, if $(z/w)^n=1$;
      - $X=\Z_{15}$, $x \sim x$, if $5(x-y)\equiv 0 \mod 15$;
      - $X=\N\times \N$, $(p,q) \sim (r,s)$, if $p+s=r+q$;
      - $X=\Z\times \N^+$, $(p,q) \sim (r,s)$, if $pr=sq$.
      #+BEGIN_COMMENT
      %\begin{enumerate}
      % - $X=\C$,  $z \sim w$, if $|z|=|w|$; 
      % - $X=\C$,  $z \sim w$, if $z/|z|=w/|w|$;
      % - $X=\C$,  $z \sim w$, if $z/w=\pm 1$;  
      % - $X=\C$,  $z \sim w$, if $z/w \in \{\pm 1, \pm i\}$;  
      % - $X=\C$,  $z \sim w$, if $(z/w)^n=1$;
      % - $X=\Z_{15}$,  $x \sim x$, if $5(x-y)\equiv 0 \mod 15$;
      % - $X=\N\times \N$,  $(p,q) \sim (r,s)$, if $p+s=r+q$;
      % - $X=\Z\times \N^+$,  $(p,q) \sim (r,s)$, if $pr=sq$. 
      %\end{enumerate}
      #+END_COMMENT

   7. Write a program which decides if a relation is reflexive
      (symmetric, anti-symmetric, transitive) or not. Count the number of
      equivalence relations, and the number of partial orderings defined
      on a four element set using the program.

   8. Adam and Bob are playing the following game: First Adam selects a
      subset of the $X=\{1, 2, 3\}$ set, then Bob selects a subset of
      $X$, than again Adam and so on.  But they must never select a
      subset which was a subset of a previously selected (sub)set.  The
      loser is the one who makes the last move, which has to be
      selecting the entire $X$ set.  A possible game play: $A: \{1\}$,
      $B: \{2\}$, $A: \{1, 3\}$, $B:\{2,3\}$, $A:\{1,2\}$,
      $B:\{1,2,3\}$, and Adam wins. What is the winning strategy?
   9. On the set $\mathbb{N} \times \mathbb{N}$ let us define a relation
      $\mathbf{R}$ the following way: $(m_1,n_1)\mathbf{R}(m_2,n_2)$, if
      $m_1 \le m_2$ and $n_1 \le n_2$. Show that $\mathbf{R}$ is a
      partial ordering.
  
   10. Is the following relation a function? $\textbf{R} \subset A \times
       A$, where $A$ is the set of lines in the plane; $a\textbf{R}b$, if
       the lines $a$ and $b$ form an angle of $60^\circ$: Examine the
       properties of this relation (are they: reflexive, transitive,
       symmetric?).

   11. Let $A$ be the set of equilateral triangles, which have a
       predefined height $m > 0$ associated with the base of the
       triangle, $B = \{b: b > 0, b\in\mathbb{R}\}$. Let us define the
       relation $\textbf{R} \subseteq A \times B$ as follows:
       $a\textbf{R}b, a \in A, b \in B$, if the area of triangle $a$
       equals $b$. Show that \textbf{R} is a function, and examine its
       properties (is it injective, surjective, bijective).

   12. Determine the domain, range of the following relations, decide if
       they and their inverses are functions or not:
       - $\{(x,y)\in \mathbb{R}^2:a<x<b,x<y<2x\}$, where $a,b\in
         \mathbb{R}$ are given numbers;
       - $\{(x,y)\in \mathbb{R}^2:y(1-x^2)=x-1\}$,
       - $\{(x,y)\in \mathbb{R}^2:y=(x-1)/(1-x^2)\}$;
       - $\{(x,y)\in \mathbb{R}^2:|x|+|y|\le 1\}$;
       - $\{(x,y)\in \mathbb{R}^2:x^2=1+y^2,y>0\}$;
       - $\{(x,y)\in \mathbb{R}^2:x^2+y^2-2y<0\}$.

   13. Consider the function $f(x) = x/(1-x)$.  It cannot be defined for
       the entire number line.  Which is the widest subset of real
       numbers, for which $f$ can be defined?  Is this function
       injective/surjective/bijective on this subset of real numbers?
       What is the widest subset of $\mathbb{R}$, for which every
       composition $f, f\circ f, f\circ f\circ f, \ldots$ can be defined?
       What can we say about the connection of $f\circ f \circ f$ and
       $f$?

   14. For the given relations on $\mathbf{R}$ determine $\dmn
       (\mathbf{R})$, $\rng (\mathbf{R})$. For $A=\{0,1,2\}$ determine the
       image of $A$ i.e. $\mathbf{R}(A)$, preimage $\mathbf{R}^{-1}(A)$,
       restriction $\mathbf{R}\mid_A$:
       1) $\mathbf{R}=\{(x,y)\in\mathbb{Z}_3\times\mathbb{Z}_3: y^2=x\}$, 
       2) $\mathbf{R}=\{(x,y)\in\mathbb{Z}_4\times\mathbb{Z}_4: y^2=x^2\}$, 
       3) $\mathbf{R}=\{(x,y)\in \mathbb{Z}_5\times\mathbb{Z}_5:y^2=x^3+x+1\}$, 
       4) $\mathbf{R}=\{(x,y)\in \mathbb{Z}_7\times\mathbb{Z}_7:y^2=x^3+2\}$.

   15. Determine $\mathbf{S}\circ \mathbf{R}$ and $\mathbf{R}\circ
       \mathbf{S}$, if

       - $\mathbf{R}=\{(x,y)\in\mathbb{Z}_3\times\mathbb{Z}_3: y^2=x\}$ and
         $\mathbf{S}=\{(x,y)\in\mathbb{Z}_3\times\mathbb{Z}_3:y=2x\}$;
       - $\mathbf{R}=\{(x,y)\in\mathbb{Z}_4\times\mathbb{Z}_4: y^2=x^2\}$
         and $\mathbf{S}=\{(x,y)\in\mathbb{Z}_4\times\mathbb{Z}_4:y=2x\}$;
       - $\mathbf{R}=\{(x,y)\in\mathbb{Z}_5\times\mathbb{Z}_5:
         y^2=x^3+x+1\}$ and
         $\mathbf{S}=\{(x,y)\in\mathbb{Z}_5\times\mathbb{Z}_5:y^2=x^3+1\}$;
       - $\mathbf{R}=\{(x,y)\in\mathbb{Z}_6\times\mathbb{Z}_6: xy=0\}$ and
         $\mathbf{S}=\{(x,y)\in\mathbb{Z}_6\times\mathbb{Z}_6:x^2+y^2=0\}$;
       - $\mathbf{R}=\{(x,y)\in\mathbb{Z}_7\times\mathbb{Z}_7: xy=1\}$ and
         $\mathbf{S}=\{(x,y)\in\mathbb{Z}_7\times\mathbb{Z}_7:x^2+y^2=1\}$;
       - $\mathbf{R}=\{(x,y)\in\mathbb{Z}_8\times\mathbb{Z}_8: x^2y^2=0\}$
         and $\mathbf{S}=\{(x,y)\in\mathbb{Z}_8\times\mathbb{Z}_8:
         x^2+y^2=0\}$;
 
   16. Determine the domain, range, of the following relations, determine
       if they are functions and if their inverses are functions:
       - $\mathbf{R}=\{(x,y)\in\mathbb{Z}_5\times\mathbb{Z}_5: x\cdot y=1\}$;
       - $\mathbf{R}=\{(x,y)\in\mathbb{Z}_6\times\mathbb{Z}_6: x\cdot y=1\}$; 
       - $\mathbf{R}=\{(x,y)\in\mathbb{Z}_5\times\mathbb{Z}_5: x^2+y^2=1\}$; 
       - $\mathbf{R}=\{(x,y)\in\mathbb{Z}_5\times\mathbb{Z}_5: x^4-x=y\}$; 
       - $\mathbf{R}=\{(x,y)\in\mathbb{Z}_7\times\mathbb{Z}_{12}: x^4-x=y\}$; 
       - $\mathbf{R}=\{(x,y)\in\mathbb{Z}_8\times\mathbb{Z}_3: x^4-x=y\}$; 
       - $\mathbf{R}=\{(x,y)\in\mathbb{Z}_8\times\mathbb{Z}_7: x^6=y\}$.

** Relations - Solutions
  
  
