# -*- mode:org; mode: flyspell; -*-

#+SETUPFILE: ../include/practice.h.org

#+TITLE: Discrete mathematics I. practice - Number theory
#+SHORT_TITLE: Number theory

* Problems
  1. Prove that $6$ is a divisor of $n(n + 1)(2n + 1)$, where $n$ is
     an arbitrary integer.

  2. Let $m$ be an integer. Prove, that $30$ is a divisor of $m^5 -m$.
     
  3. Prove that if $a$ is an even integer no divisible by $4$, then
     $a(a^2 - 1)(a^2 - 4)$ is divisible by $960$.

  4. Prove that the sub of the cube of three consecutive integers is
     1) divisible by $3$ times the middle number; 
     2) divisible by 9.
  5. Prove that, if we take any three digit number (written in the
     decimal numeral system), and write it down two time
     consecutively, the obtained six digit number will be divisible by
     $7$, $11$ and $13$.
  6. Do the calculations in the indicated numeral system:
     #+ATTR_LATEX: :environment compactenum
     1) $10011001_{(2)}+101011010_{(2)}$; 
     2) $1001_{(2)} \cdot 1101_{(2)}$;
     3) $1221_{(3)} \cdot 2112_{(3)}$;
     4) $1234_{(5)} + 4321_{(5)}$;
     5) $1234_{(5)} \cdot 4321_{(5)}$;
     6) $1236_{(7)} + 6321_{(7)}$;
     7) $10011001_{(2)} : 101_{(2)}$; 
     8) $110110010101101_{(2)}:101111001_{(2)}$; 
     9) $12011_{(3)} : 201_{(3)}$.

  7. Using the euclidean algorithm, calculate the greatest common
     divisor and the least common multiple of the following numbers.
     #+LATEX: \begin{multicols}{2}
     #+ATTR_LATEX: :environment compactenum
     1) $a=86, b=31$; 
     2) $a=139, b=102$;
     3) $a=255, b=111$;
     4) $a=332, b=88$;
     5) $a=675, b=471$;
     6) $a=432, b=300$;
     7) $a=756, b=333$;
     8) $a=504, b=150$;
     9) $a=420, b=154$;
     10) $a=1080, b=285$;
     11) $a=2016, b=880$;
     12) $a=30, b=22$;
     13) $a=430, b=300$;
     14) $a=2355, b=450$;
     15) $a=300, b=132$;
     16) $a=518, b=154$.
     #+LATEX: \end{multicols}
  8. For $a,b\in\mathbb{Z}$ from the previous exercise, express
     the greatest common divisor in the following form $ax+by=(a,b)$.
  9. For $a,b\in\mathbb{Z}$ from the previous exercise, express
     the greatest common divisor in the following form $ax+by=(a,b)$.
  10. Solve the following Diophantine equations:
      #+LATEX: \begin{multicols}{2}
      1) $172x+62y=38$;
      2) $82x+22y=34$;
      3) $450x+86y=100$;
      4) $125x+45y=-20$.
      #+LATEX: \end{multicols}
  11. Solve the following congruences:
      1) $21x  \equiv 14 \pmod{35}$;
      2) $172x \equiv 6  \pmod{62}$; 
      3) $3x   \equiv 8  \pmod{13}$;
      4) $12x  \equiv 9  \pmod{18}$;
      5) $26x  \equiv 12 \pmod{22}$;
      6) $20x  \equiv 19 \pmod{22}$; 
      7) $16x  \equiv 36 \pmod{28}$; 
      8) $126x \equiv 46 \pmod{99}$.
  12. Find the integer solutions of the following equations using
      congruences.
      #+ATTR_LATEX: :environment inparaenum
      1) $27x+49y=3$;
      2) $33x+23y=2$; 
      3) $33x+23y=3$.
  13. Mischievous centipedes are running around on a ball. On kind has 14
      legs and the other kind 20 legs. We counted 232 legs all
      together. How many centipedes are running around on the ball?
  14. Which is the smallest natural number which ends with the digit 3
      written in the 28 base numeral system, and in the 19 base numeral
      system ends with the digit 4? Solve the problem using congruences.
  15. We have 100 forints change at the shop. How many different way can
      the cashier return our change if he only has 20 and 50 forint
      coins?
  16. Solve the following systems of congruences:
      # #+ATTR_LATEX: :environment asparablank
      # #+ATTR_LATEX: :environment compactenum
      1) 
	 \begin{align*}
	 5x &\equiv 3 \pmod{7} \\
	 3x &\equiv 7 \pmod{8} 
	 \end{align*}
      2) 
	 \begin{align*}
	 3x &\equiv 2 \pmod{4} \\
	 4x &\equiv 3 \pmod{5}
	 \end{align*}
      3) 
	 \begin{align*}
	 5x &\equiv 1 \pmod{6} \\
	 7x &\equiv 9 \pmod{10} 
	 \end{align*}
      4) 
	 \begin{align*}
	 5x &\equiv 2 \pmod{6} \\
	 7x &\equiv 3 \pmod{10}
	 \end{align*}
      5) 
	 \begin{align*}
	 x &\equiv 2 \pmod{3} \\
	 x &\equiv 3 \pmod{4} \\
	 x &\equiv 1 \pmod{5} 
	 \end{align*}
      6) 
	 \begin{align*}
	 4x &\equiv 2 \pmod{3} \\
	 3x &\equiv 2 \pmod{7} \\
	 9x &\equiv 7 \pmod{11} 
	 \end{align*}
      7) 
	 \begin{align*}
	 3x &\equiv 1 \pmod{4} \\
	 7x &\equiv 2 \pmod{9} \\
	 9x &\equiv 3 \pmod{13} 
	 \end{align*}
      8) 
	 \begin{align*}
	 5x &\equiv 3 \pmod{6} \\
	 3x &\equiv 9 \pmod{10} \\
	 8x &\equiv 9 \pmod{15} 
	 \end{align*}
  17. Which natural numbers less then 100 have the property that, when
      multiplied by 23, the obtained number written in the base 7 numeral
      system, have 5 as the last digit and 2 as the one before the last?
      Solve the problem using congruences.
  18. Using the Chinese remainder theorem, find those integers which have
      remainders 1 when divided by 3, 2 when divided by 4 and 3 when
      divided by 5.
  19. Calculate $\varphi(n)$ for $n=1,2,3,4,10,24,96, 100$!
  20. Prove that
      #+ATTR_LATEX: :environment inparaenum
      1) $n^6 - 1$ is divisible by 7, if $(n; 7) = 1$;
      2) $n^{12} - 1$ is divisible by 7, if $(n; 7) = 1$;
      3) $n^{6k} - 1$ is divisible by 7, if $(n; 7) = 1$.
  21. Show that, for every integer $x$ we have $x^7 \equiv x \pmod{42}$.
  22. Determine the last three digits of $3^{1203}$.
  23. What is the remainder of $173^{163}$ obtained by dividing it by 17.
  24. Determine the last three digits of $143^{143}$ (written in the
      decimal number system).
  25. What is the remainder of the following number when divided by
      $103$: $205^{206^{207}}$?
  26. Determine the last two digits of $37^{39^{42}}$.
  27. What are the last two digits of $17^{3^{2017}}$ when written in the
      base 8 numeral system?
  28. What are the last two digits of $11^{2013^{26}}$ when written in
      the decimal number system?
  29. What is the smallest non-negative remainder of
      #+ATTR_LATEX: :environment inparaenum
      1) $323^{149}$ when divided by 63;
      2) $423^{173}$ when divided by 52;
      3) $495^{173}$ when divided by 98;
      4) $457^{101}$ when divided by 90?
  30. Prove that $n^{13} - n$ is divisible by $2$, $3$, $5$, $7$ and
      $13$ for every integer $n$ .
  31. Solve the following congruences using the Euler-Fermat theorem:
      #+ATTR_LATEX: :environment inparaenum
      1) $21x  \equiv 14 \pmod{35}$;
      2) $172x \equiv 6  \pmod{62}$;
      3) $3x   \equiv 8  \pmod{13}$;
      4) $12x  \equiv 9  \pmod{18}$.
  32. Show that $a^{1729}\equiv a \pmod{1729}$ although 1729 is not prime.

* Solutions
  
  Divisibility: we say that $a$ divides $b$ ($a,b \in \mathbb{Z}$) if
  $\exists k \in \mathbb{Z}$ so that $ak=b$ and we write $a \mid b$
  (if $a$ doesn't divide $b$ then we write $a \nmid b$).

  1. Let $N=n(n + 1)(2n + 1)$, and to show that $6 \mid N$ we have to
     show that $2 \mid N$ and $3 \mid N$.  If $n$ is even, then $2
     \mid N$, if $n$ is odd, then $2 \mid n+1$, so $2 \mid N$.  If $3
     \mid n$, we are done, if not, then $n = 3k+1$ or $n = 3k+2$ (for
     some integer $k$).  If $n = 3k + 2$ then $n + 1 = 3k + 2 + 1 =
     3k + 3$ which is divisible by 3, and if $n = 3k + 1$ then $2n + 1
     = 2(3k+1) +1 = 6k + 2 + 1 = 6k + 3$ which is also divisible
     by 3. So $N$ is divisible by 2 and 3 so it is divisible by 6.

  2. $M=m^5-m$. To prove that $30 \mid M$ we need to show that $2 \mid
     M$, $3 \mid M$ and $5 \mid M$. 

     $M= m (m^4 - 1) = m (m^2 -1 ) (m^2 + 1) = m (m-1)(m+1) (m^2 +
     1)$.  So it is trivial that $2 \mid M$ and $3 \mid M$ because,
     $m-1$, $m$ and $m+1$ are three consecutive numbers, \ie at least
     one of them has to be divisible by 2 and at least one by 3.
     
     #+BEGIN_SRC C
       int i;
       int n = 5;
       for(i=0; i<n; i++)
         printf("%d mod %d = %d\n", i, 3, i%3);
     #+END_SRC

     #+RESULTS:
     | 0 | mod | 3 | = | 0 |
     | 1 | mod | 3 | = | 1 |
     | 2 | mod | 3 | = | 2 |
     | 3 | mod | 3 | = | 0 |
     | 4 | mod | 3 | = | 1 |

     But how to show that $5 \mid M$? So $m=5k$ or $m=5k \pm 1$ or
     $m=5k\pm2$ ($k\in\mathbb{Z}$).  So if $m=5k$ then $5 \mid M$, if
     $m=5k+1$ then $5 \mid m-1 \mid M$, if $m=5k-1$ then $5 \mid m+1
     \mid M$, if $m = 5k \pm 2$ then $m^2 = 25k^2 \pm 20 k + 4$, so
     $m^2 + 1 = 25k^2 \pm 20 k + 4 +1$ which is divisible by 5. So we
     are done, bye bye!

  3. 

  4. 

  5. 

  6. 

  7. 

  8. 

  9. 

  10. 

  11. 

  12. 

  13. 

  14. 

  15. 

  16. 

  17. 

  18. 

  19. 

  20. 

  21. 

  22. The last three digits are $x = 3^{1203} \bmod 1000$, which is a
      solution of $x\equiv 3^{1203} \pmod{1000}$.  We can calculate,
      that $\varphi(1000)=400$ and by the Euler-Fermat theorem
      $3^{400} \equiv 1 \pmod{1000}$, so $x \equiv 3^{1203} =
      3^{400\cdot 3 + 3} = (3^{400})^{3}\cdot 3^3 \equiv 1^3\cdot 3^3
      = 27 \pmod{1000}$.  So the last three digits of the mentioned
      numbere are 027.

  23. $17$ is prime so, $\varphi(17)=16$.  $163 \bmod 16 = 3$, so $x
      \equiv 173^{163} \equiv 3^{163} = 3^{q\cdot16+3} =
      (3^{16})^{q}\cdot 3^3 \equiv 1^q \cdot 3^{3} =27 \pmod{17}$.

  24. 

  25. $103$ is prime, so $\varphi(103)=102$.  So we calculate $x
      \equiv 205^{206^{207}} \equiv (-1)^{206^{207}} = (-1)^{q \cdot
      102 + r} = ((-1)^{102})^{q} \cdot (-1)^r = (-1)^{r} \pmod{103}$
      where $r \equiv 206^{207} \pmod{102}$. $r$ cannot be odd, so $r$
      is even, which means that $x\equiv 1 \pmod{103}$.

      #+BEGIN_SRC python :exports none
        return 2012%16 
      #+END_SRC

      #+RESULTS:
      : 12
